version: 2
updates:
  # 1) NPM dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "06:00"
    commit-message:
      prefix: chore(deps)
    rebase-strategy: auto
    labels:
      - dependencies
      - automated-update
      - dependabot
    target-branch: dependabot-release/main

  # 2) GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "06:00"
    commit-message:
      prefix: chore(deps)
    rebase-strategy: auto
    labels:
      - dependencies
      - automated-update
      - dependabot
    target-branch: dependabot-release/main
