const INDEX_HEADER = `// Auto-generated file - do not edit manually
// Generated by Conversational CMS module

import type { Project } from '../../shared/types/project'
`

export const renderProjectIndexFile = (slugs: string[]) => {
	const sorted = [...new Set(slugs)].sort((a, b) => a.localeCompare(b))

	const imports = sorted
		.map((slug, index) => `import project${index} from './${slug}'`)
		.join('\n')

	const entries = sorted
		.map((slug, index) => `  '${slug}': { ...project${index}, slug: '${slug}' },`)
		.join('\n')

	return `${INDEX_HEADER}
${imports}

const projects: Record<string, Project> = {
${entries}
} as const

export default projects

export type ProjectKey = keyof typeof projects
`
}
