// Auto-generated file - do not edit manually
// Generated by scripts/generateProjectIndex.js

import type { Project } from '~~/shared/types/project';

import project0 from './example copy';
import project1 from './example';

/**
 * Exported project data modules indexed by filename with slug properties
 * 
 * @description Runtime-accessible mapping of all project data files.
 * Each project object is enhanced with a 'slug' property derived from its filename.
 * This enables URL-friendly routing and identification of projects.
 * All projects conform to the Project type interface.
 * 
 * @example
 * // Access project by key
 * const project = projects['kitchen-modern']
 * console.log(project.slug) // "kitchen-modern"
 * 
 * // Get all project slugs  
 * const slugs = Object.keys(projects) as ProjectKey[]
 */
const projects: Record<string, Project> = {
  'example-copy': { ...project0, slug: 'example-copy' },
  'example': { ...project1, slug: 'example' },
} as const;

export default projects;

/**
 * Type representing valid project keys (slugs)
 * @description Union type of all available project slugs
 */
export type ProjectKey = keyof typeof projects;
