# Lint and typecheck the project and creates a preview deployment
name: Code Quality and Preview Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm nuxi prepare
      - run: pnpm lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm nuxi prepare
      - run: pnpm typecheck
  
  # preview:
  #   needs: [lint, typecheck]
  #   uses: ./.github/workflows/nuxthub.yml
  #   with:
  #     environment: preview
  #   secrets: inherit  # Important for environment variables to be passed to the workflow