name: Code Quality

on:
  workflow_call: {} # reusable
  workflow_dispatch: {} # (optional)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node & dependencies
        uses: ./.github/actions/setup

      - run: pnpm nuxi prepare
      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & dependencies
        uses: ./.github/actions/setup

      - run: pnpm nuxi prepare
      - run: pnpm typecheck
