name: Preview Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    # needs: []  # We'll add the code quality dependency here once we confirm it works
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm nuxi prepare
      - name: Preview deployment placeholder
        run: echo "placeholder step for preview deployments"