name: Preview Deployment

on:
  workflow_call: {}        # reusable
  workflow_dispatch: {}    # (optional)

permissions:
  id-token: write          # Required for OIDC authentication
  contents: read           # Required for checkout
  
jobs:
  preview:
    uses: ./.github/workflows/nuxthub.yml
    with:
      environment: preview
    secrets: inherit  # Important for environment variables to be passed to the workflow