name: Preview Deployment

on:
  workflow_run:
    workflows: ["Code Quality"]
    types:
      - completed

jobs:
  preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm nuxi prepare
      - name: Preview deployment placeholder
        run: echo "placeholder step for preview deployments"